# Generated by Django 4.2.3 on 2025-12-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LiturgyFlower",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("image", models.ImageField(max_length=1000, upload_to="liturgy_flower/image/", verbose_name="이미지")),
            ],
            options={
                "verbose_name": "전례꽃",
                "verbose_name_plural": "전례꽃",
                "db_table": "liturgy_flower",
                "ordering": ["-created_at"],
            },
        ),
    ]
