# Generated by Django 4.2.3 on 2025-12-12 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liturgy_flower", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="liturgyflower",
            name="image",
        ),
        migrations.CreateModel(
            name="LiturgyFlowerImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("image", models.ImageField(max_length=1000, upload_to="liturgy_flower/image/", verbose_name="이미지")),
                (
                    "liturgy_flower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liturgy_flower.liturgyflower",
                        verbose_name="전례꽃",
                    ),
                ),
            ],
            options={
                "verbose_name": "이미지",
                "verbose_name_plural": "이미지",
                "db_table": "liturgy_flower_image",
                "ordering": ["-created_at"],
            },
        ),
    ]
