# Generated by Django 5.1 on 2025-12-18 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liturgy_flower", "0001_initial"),
        ("user", "0004_alter_user_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiturgyFlowerComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("body", models.CharField(max_length=500, verbose_name="내용")),
                ("is_modified", models.BooleanField(default=False, editable=False, verbose_name="수정여부")),
                ("is_deleted", models.BooleanField(default=False, editable=False, verbose_name="삭제여부")),
                (
                    "liturgy_flower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liturgy_flower.liturgyflower",
                        verbose_name="전례꽃",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_set",
                        related_query_name="child",
                        to="liturgy_flower.liturgyflowercomment",
                        verbose_name="부모 댓글",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user", verbose_name="유저"),
                ),
            ],
            options={
                "verbose_name": "전례꽃 댓글",
                "verbose_name_plural": "전례꽃 댓글",
                "db_table": "liturgy_flower_comment",
                "ordering": ["-created_at"],
            },
        ),
    ]
