# Generated by Django 5.1 on 2025-12-18 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liturgy_flower", "0002_liturgyflowercomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="liturgyflower",
            name="comment_count",
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name="댓글수"),
        ),
        migrations.AlterField(
            model_name="liturgyflowerimage",
            name="liturgy_flower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_set",
                related_query_name="image",
                to="liturgy_flower.liturgyflower",
                verbose_name="전례꽃",
            ),
        ),
    ]
