# Generated by Django 4.2.3 on 2025-12-15 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_user_is_active"),
        ("liturgy_flower", "0002_remove_liturgyflower_image_liturgyflowerimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="liturgyflower",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="user.user", verbose_name="유저"
            ),
            preserve_default=False,
        ),
    ]
