# Generated by Django 5.1 on 2025-12-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liturgy_flower", "0003_liturgyflower_comment_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="liturgyflower",
            name="hit_count",
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name="조회수"),
        ),
        migrations.AddField(
            model_name="liturgyflower",
            name="like_count",
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name="좋아요수"),
        ),
    ]
