# Generated by Django 5.1 on 2026-01-02 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("liturgy_flower", "0004_liturgyflower_hit_count_liturgyflower_like_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="liturgyflowerimage",
            options={"ordering": ["created_at"], "verbose_name": "이미지", "verbose_name_plural": "이미지"},
        ),
    ]
