# Generated by Django 4.2.3 on 2025-12-12 03:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("body", ckeditor_uploader.fields.RichTextUploadingField(verbose_name="본문")),
                ("image", models.ImageField(max_length=1000, upload_to="event/", verbose_name="이미지")),
                ("youtube_link", models.URLField(max_length=1000, verbose_name="유튜브 링크")),
            ],
            options={
                "verbose_name": "행사",
                "verbose_name_plural": "행사",
                "db_table": "event",
                "ordering": ["-created_at"],
            },
        ),
    ]
