# Generated by Django 5.1 on 2025-12-16 02:23

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("thumbnail", models.ImageField(max_length=1000, upload_to="event/thumbnail/", verbose_name="썸네일")),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("body", django_ckeditor_5.fields.CKEditor5Field(verbose_name="본문")),
                ("youtube_link", models.URLField(blank=True, max_length=1000, null=True, verbose_name="유튜브 링크")),
            ],
            options={
                "verbose_name": "행사",
                "verbose_name_plural": "행사",
                "db_table": "event",
                "ordering": ["-created_at"],
            },
        ),
    ]
