# Generated by Django 4.2.3 on 2025-12-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="image",
        ),
        migrations.AlterField(
            model_name="event",
            name="youtube_link",
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name="유튜브 링크"),
        ),
    ]
