# Generated by Django 4.2.3 on 2025-12-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_remove_event_image_alter_event_youtube_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="thumbnail",
            field=models.ImageField(default="", max_length=1000, upload_to="event/thumbnail/", verbose_name="썸네일"),
            preserve_default=False,
        ),
    ]
