# Generated by Django 5.1 on 2026-01-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weekly_bulletin_editorial", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyBulletinEditorialDraft",
            fields=[],
            options={
                "verbose_name": "주보7면 편집",
                "verbose_name_plural": "주보7면 편집",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("weekly_bulletin_editorial.weeklybulletineditorial",),
        ),
        migrations.CreateModel(
            name="WeeklyBulletinEditorialFinal",
            fields=[],
            options={
                "verbose_name": "주보7면 최종본",
                "verbose_name_plural": "주보7면 최종본",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("weekly_bulletin_editorial.weeklybulletineditorial",),
        ),
        migrations.CreateModel(
            name="WeeklyBulletinEditorialTemplate",
            fields=[],
            options={
                "verbose_name": "주보7면 양식",
                "verbose_name_plural": "주보7면 양식",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("weekly_bulletin_editorial.weeklybulletineditorial",),
        ),
        migrations.AddField(
            model_name="weeklybulletineditorial",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name="order"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weeklybulletineditorial",
            name="state",
            field=models.PositiveIntegerField(
                choices=[(1, "편집"), (2, "최종본"), (3, "양식")], default=1, verbose_name="상태"
            ),
        ),
    ]
