# Generated by Django 5.1 on 2026-01-02 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weekly_bulletin_editorial", "0002_weeklybulletineditorialdraft_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weeklybulletineditorialdraft",
            options={"verbose_name": "주보7면 편집본", "verbose_name_plural": "주보7면 편집본"},
        ),
        migrations.CreateModel(
            name="WeeklyBulletinEditorialFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "file",
                    models.FileField(max_length=1000, upload_to="weekly_bulletin_editorial/file/", verbose_name="자료"),
                ),
                (
                    "weekly_bulletin_editorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_set",
                        related_query_name="file",
                        to="weekly_bulletin_editorial.weeklybulletineditorial",
                        verbose_name="주보7면",
                    ),
                ),
            ],
            options={
                "verbose_name": "주보7면 파일",
                "verbose_name_plural": "주보7면 파일",
                "db_table": "weekly_bulletin_editorial_file",
            },
        ),
    ]
