# Generated by Django 5.1 on 2026-01-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weekly_bulletin_editorial", "0003_alter_weeklybulletineditorialdraft_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyeongdoDocument",
            fields=[],
            options={
                "verbose_name": "명도회 자료실",
                "verbose_name_plural": "명도회 자료실",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("weekly_bulletin_editorial.weeklybulletineditorial",),
        ),
        migrations.AlterField(
            model_name="weeklybulletineditorial",
            name="state",
            field=models.PositiveIntegerField(
                choices=[(1, "명도회"), (2, "편집"), (3, "최종본"), (4, "양식")], default=1, verbose_name="상태"
            ),
        ),
    ]
