# Generated by Django 5.1 on 2026-01-05 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_remove_user_model_test"),
        ("weekly_bulletin_editorial", "0004_myeongdodocument_alter_weeklybulletineditorial_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="myeongdodocument",
            options={"verbose_name": "명도회 자료", "verbose_name_plural": "명도회 자료"},
        ),
        migrations.AlterModelOptions(
            name="weeklybulletineditorial",
            options={"ordering": ["-created_at"], "verbose_name": "주보7면", "verbose_name_plural": "주보7면"},
        ),
        migrations.AddField(
            model_name="weeklybulletineditorial",
            name="user",
            field=models.ForeignKey(
                default=5, on_delete=django.db.models.deletion.CASCADE, to="user.user", verbose_name="유저"
            ),
        ),
    ]
