# Generated by Django 5.1 on 2026-01-05 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_remove_user_model_test"),
        ("weekly_bulletin_editorial", "0005_alter_myeongdodocument_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklybulletineditorial",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user", verbose_name="유저"),
        ),
    ]
