# Generated by Django 5.1 on 2026-01-07 03:27

import app.common.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weekly_bulletin_editorial", "0006_alter_weeklybulletineditorial_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklybulletineditorialfile",
            name="file",
            field=models.FileField(
                max_length=1000,
                storage=app.common.storages.DownloadableMediaStorage(),
                upload_to="weekly_bulletin_editorial/file/",
                verbose_name="자료",
            ),
        ),
    ]
