# Generated by Django 4.2.3 on 2025-12-15 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0009_alter_user_is_active"),
        ("weekly_bulletin", "0005_weeklybulletin_hit_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyBulletinHit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP 주소")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                        verbose_name="유저",
                    ),
                ),
                (
                    "weekly_bulletin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weekly_bulletin.weeklybulletin",
                        verbose_name="자유 게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "주보 조회",
                "verbose_name_plural": "주보 조회",
                "db_table": "weekly_bulletin_hit",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="weeklybulletinhit",
            constraint=models.UniqueConstraint(
                fields=("weekly_bulletin", "user"), name="unique_weekly_bulletin_user_hit"
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklybulletinhit",
            constraint=models.UniqueConstraint(
                fields=("weekly_bulletin", "ip_address"), name="unique_weekly_bulletin_ip_hit"
            ),
        ),
    ]
