# Generated by Django 5.1 on 2025-12-31 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("department_board_comment", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DepartmentBoardComment",
        ),
    ]
