# Generated by Django 5.1 on 2026-01-07 02:59

from django.db import migrations, models

import app.common.storages


class Migration(migrations.Migration):

    dependencies = [
        ("weekly_bulletin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklybulletin",
            name="file",
            field=models.FileField(
                max_length=1000,
                storage=app.common.storages.DownloadableMediaStorage(),
                upload_to="weekly_bulletin/file/",
                verbose_name="주보 파일",
            ),
        ),
    ]
