# Generated by Django 4.2.3 on 2025-12-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weekly_bulletin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklybulletin",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="승인여부"),
        ),
    ]
