# Generated by Django 4.2.3 on 2025-12-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weekly_bulletin", "0002_weeklybulletin_is_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weeklybulletin",
            name="is_approved",
        ),
    ]
