# Generated by Django 4.2.3 on 2025-12-12 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_rename_is_accepted_user_is_approved"),
        ("weekly_bulletin", "0003_remove_weeklybulletin_is_approved"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyBulletinRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("file", models.FileField(max_length=1000, upload_to="weekly_bulletin/file/", verbose_name="주보 파일")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user")),
            ],
            options={
                "verbose_name": "주보 원고 접수",
                "verbose_name_plural": "주보 원고 접수",
                "db_table": "weekly_bulletin_request",
                "ordering": ["-created_at"],
            },
        ),
    ]
