# Generated by Django 4.2.3 on 2025-12-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weekly_bulletin", "0004_weeklybulletinrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklybulletin",
            name="hit_count",
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name="조회수"),
        ),
        migrations.DeleteModel(
            name="WeeklyBulletinRequest",
        ),
    ]
