# Generated by Django 5.1 on 2025-12-18 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("liturgy_flower", "0004_liturgyflower_hit_count_liturgyflower_like_count"),
        ("user", "0004_alter_user_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiturgyFlowerLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "liturgy_flower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liturgy_flower.liturgyflower",
                        verbose_name="전례꽃",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user", verbose_name="유저"),
                ),
            ],
            options={
                "verbose_name": "전례꽃 좋아요",
                "verbose_name_plural": "전례꽃 좋아요",
                "db_table": "liturgy_flower_like",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("liturgy_flower", "user"), name="unique_liturgy_flower_likes")
                ],
            },
        ),
    ]
