# Generated by Django 5.1 on 2025-12-31 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pastor_history", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pastorhistory",
            name="model_test",
            field=models.CharField(default="a", verbose_name="test"),
            preserve_default=False,
        ),
    ]
