# Generated by Django 5.1 on 2025-12-31 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pastor_history", "0002_pastorhistory_model_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pastorhistory",
            name="model_test",
        ),
    ]
