# Generated by Django 4.2.3 on 2025-12-12 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="유저네임")),
                ("password", models.CharField(max_length=128, verbose_name="비밀번호")),
                ("name", models.CharField(max_length=20, verbose_name="이름")),
                ("baptismal_name", models.CharField(max_length=40, verbose_name="세례명")),
                ("postcode", models.CharField(max_length=6, verbose_name="우편번호")),
                ("base_address", models.CharField(max_length=200, verbose_name="기본주소")),
                ("detail_address", models.CharField(max_length=200, verbose_name="상세주소")),
                ("birth", models.DateField(verbose_name="생년월일")),
                ("is_accepted", models.BooleanField(default=False, verbose_name="가입승인 여부")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="department.department", verbose_name="분과"
                    ),
                ),
            ],
            options={
                "verbose_name": "유저",
                "verbose_name_plural": "유저",
                "db_table": "user",
            },
        ),
    ]
