# Generated by Django 5.1 on 2025-12-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0002_subdepartment"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="department_set",
        ),
        migrations.AddField(
            model_name="user",
            name="sub_department_set",
            field=models.ManyToManyField(blank=True, to="department.subdepartment", verbose_name="세부분과"),
        ),
    ]
