# Generated by Django 4.2.3 on 2025-12-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="grade",
            field=models.PositiveIntegerField(
                choices=[(1, "1등급"), (2, "2등급"), (3, "3등급"), (4, "4등급"), (5, "5등급")], default=1, verbose_name="등급"
            ),
            preserve_default=False,
        ),
    ]
