# Generated by Django 4.2.3 on 2025-12-12 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_grade"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_accepted",
            new_name="is_approved",
        ),
    ]
