# Generated by Django 5.1 on 2025-12-31 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="model_test",
            field=models.CharField(default="a", verbose_name="model_test"),
            preserve_default=False,
        ),
    ]
