# Generated by Django 4.2.3 on 2025-12-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0001_initial"),
        ("user", "0004_rename_is_accepted_user_is_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="department",
        ),
        migrations.AddField(
            model_name="user",
            name="department_set",
            field=models.ManyToManyField(blank=True, to="department.department", verbose_name="분과"),
        ),
    ]
