# Generated by Django 5.1 on 2025-12-31 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_user_model_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="model_test",
        ),
    ]
