# Generated by Django 4.2.3 on 2025-12-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_remove_user_department_user_department_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="grade",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1등급"),
                    (2, "2등급"),
                    (3, "3등급"),
                    (4, "4등급"),
                    (5, "5등급"),
                    (6, "6등급"),
                    (7, "7등급"),
                    (8, "8등급"),
                    (9, "9등급"),
                    (10, "10등급"),
                ],
                default=10,
                verbose_name="등급",
            ),
        ),
    ]
