# Generated by Django 4.2.3 on 2025-12-12 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_grade"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_approved",
            new_name="is_active",
        ),
    ]
