# Generated by Django 4.2.3 on 2025-12-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_rename_is_approved_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="grade",
            field=models.PositiveIntegerField(
                choices=[(1, "총관리자"), (2, "관리자"), (3, "사제 및 수도자"), (4, "단체장"), (5, "본당 신자")],
                default=5,
                verbose_name="등급",
            ),
        ),
    ]
