# Generated by Django 4.2.3 on 2025-12-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_user_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False, editable=False, verbose_name="가입승인 여부"),
        ),
    ]
