# Generated by Django 5.1 on 2026-01-06 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ["-created_at"], "verbose_name": "본당일정", "verbose_name_plural": "본당일정"},
        ),
    ]
