# Generated by Django 5.1 on 2026-01-07 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ["-created_at"], "verbose_name": "본당소식", "verbose_name_plural": "본당소식"},
        ),
    ]
