# Generated by Django 5.1 on 2026-01-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_news_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="전체공개"),
        ),
    ]
