# Generated by Django 5.1 on 2025-12-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssistantPriestHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("order", models.PositiveIntegerField(db_index=True, editable=False, verbose_name="order")),
                ("assistant_system", models.CharField(max_length=50, verbose_name="보좌 체제")),
                ("category", models.CharField(max_length=50, verbose_name="구분")),
                ("name", models.CharField(max_length=20, verbose_name="이름")),
                ("baptismal_name", models.CharField(max_length=40, verbose_name="세례명")),
                ("start_date", models.DateField(verbose_name="재임 시작일")),
                ("end_date", models.DateField(verbose_name="재임 종료일")),
            ],
            options={
                "verbose_name": "역대 부주임/보좌신부",
                "verbose_name_plural": "역대 부주임/보좌신부",
                "db_table": "assistant_priest_history",
                "ordering": ["order"],
            },
        ),
    ]
