# Generated by Django 5.1 on 2025-12-31 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant_priest_history", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistantpriesthistory",
            name="assistant_system",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="보좌 체제"),
        ),
    ]
