# Generated by Django 4.2.3 on 2025-12-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("order", models.PositiveIntegerField(db_index=True, editable=False, verbose_name="order")),
                ("name", models.CharField(help_text="관리용", max_length=100, verbose_name="배너명")),
                ("image", models.ImageField(max_length=1000, upload_to="banner/image/", verbose_name="이미지")),
            ],
            options={
                "verbose_name": "배너",
                "verbose_name_plural": "배너",
                "db_table": "banner",
                "ordering": ["order"],
            },
        ),
    ]
