# Generated by Django 5.1 on 2025-12-16 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PassingNotice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "portrait",
                    models.ImageField(max_length=1000, upload_to="passing_notice/portrait/", verbose_name="고인 사진"),
                ),
                ("name", models.CharField(max_length=20, verbose_name="고인 성함")),
                ("baptismal_name", models.CharField(max_length=40, verbose_name="고인 세례명")),
                ("age", models.PositiveIntegerField(verbose_name="고인 나이")),
                ("passing_at", models.DateTimeField(verbose_name="선종일시")),
                ("funeral_start_at", models.DateField(verbose_name="장례 시작일")),
                ("funeral_end_at", models.DateField(verbose_name="장례 종료일")),
                ("funeral_mass_at", models.DateField(verbose_name="장례미사 일정")),
                ("funeral_mass_location", models.CharField(max_length=200, verbose_name="장례미사 장소")),
                ("funeral_hall_address", models.CharField(max_length=200, verbose_name="빈소 위치")),
                ("chief_mourner", models.CharField(max_length=20, verbose_name="상주")),
                ("encoffinment_at", models.DateTimeField(verbose_name="입관 일정")),
                ("departure_at", models.DateTimeField(verbose_name="발인 일정")),
            ],
            options={
                "verbose_name": "선종 안내",
                "verbose_name_plural": "선종 안내",
                "db_table": "passing_notice",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PassingNoticeComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("body", models.CharField(max_length=500, verbose_name="내용")),
                ("is_deleted", models.BooleanField(default=False, editable=False, verbose_name="삭제여부")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_set",
                        related_query_name="child",
                        to="passing_notice.passingnoticecomment",
                        verbose_name="부모 댓글",
                    ),
                ),
                (
                    "passing_notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="passing_notice.passingnotice",
                        verbose_name="선종 안내 댓글",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user", verbose_name="유저"),
                ),
            ],
            options={
                "verbose_name": "선종 안내 댓글",
                "verbose_name_plural": "선종 안내 댓글",
                "db_table": "passing_notice_comment",
                "ordering": ["-created_at"],
            },
        ),
    ]
