# Generated by Django 4.2.3 on 2025-12-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PassingNotice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "portrait",
                    models.ImageField(max_length=1000, upload_to="passing_notice/portrait/", verbose_name="고인 사진"),
                ),
                ("name", models.CharField(max_length=20, verbose_name="고인 성함")),
                ("baptismal_name", models.CharField(max_length=40, verbose_name="고인 세례명")),
                ("passing_at", models.DateTimeField(verbose_name="선종일시")),
                ("funeral_start_at", models.DateField(verbose_name="장례 시작일")),
                ("funeral_end_at", models.DateField(verbose_name="장례 종료일")),
                ("funeral_hall_address", models.CharField(max_length=200, verbose_name="빈소 위치")),
                ("encoffinment_at", models.DateTimeField(verbose_name="입관 일정")),
                ("departure_at", models.DateTimeField(verbose_name="발인 일정")),
            ],
            options={
                "verbose_name": "선종 안내",
                "verbose_name_plural": "선종 안내",
                "db_table": "passing_notice",
                "ordering": ["-created_at"],
            },
        ),
    ]
