# Generated by Django 4.2.3 on 2025-12-12 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_rename_is_accepted_user_is_approved"),
        ("passing_notice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PassingNoticeComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("body", models.CharField(max_length=500, verbose_name="내용")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="삭제여부")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_set",
                        related_query_name="child",
                        to="passing_notice.passingnoticecomment",
                        verbose_name="부모 댓글",
                    ),
                ),
                (
                    "passing_notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="passing_notice.passingnotice",
                        verbose_name="선종 안내 댓글",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user", verbose_name="유저"),
                ),
            ],
            options={
                "verbose_name": "선종 안내 댓글",
                "verbose_name_plural": "선종 안내 댓글",
                "db_table": "passing_notice_comment",
                "ordering": ["-created_at"],
            },
        ),
    ]
