# Generated by Django 5.1 on 2025-12-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passing_notice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="passingnoticecomment",
            name="is_modified",
            field=models.BooleanField(default=False, editable=False, verbose_name="수정여부"),
        ),
    ]
