# Generated by Django 4.2.3 on 2025-12-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passing_notice", "0002_passingnoticecomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passingnoticecomment",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False, verbose_name="삭제여부"),
        ),
    ]
