# Generated by Django 5.1 on 2025-12-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("passing_notice", "0002_passingnoticecomment_is_modified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passingnoticecomment",
            name="parent",
        ),
    ]
