# Generated by Django 4.2.3 on 2025-12-15 03:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passing_notice", "0003_alter_passingnoticecomment_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="passingnotice",
            name="age",
            field=models.PositiveIntegerField(default=0, verbose_name="고인 나이"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="passingnotice",
            name="chief_mourner",
            field=models.CharField(default="", max_length=20, verbose_name="상주"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="passingnotice",
            name="funeral_mass_at",
            field=models.DateField(default=django.utils.timezone.localtime, verbose_name="장례미사 일정"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="passingnotice",
            name="funeral_mass_location",
            field=models.CharField(default="", max_length=200, verbose_name="장례미사 장소"),
            preserve_default=False,
        ),
    ]
