# Generated by Django 5.1 on 2025-12-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passing_notice", "0003_remove_passingnoticecomment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="passingnotice",
            name="comment_count",
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name="댓글수"),
        ),
    ]
