# Generated by Django 5.1 on 2025-12-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passing_notice", "0004_passingnotice_comment_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passingnotice",
            name="chief_mourner",
            field=models.CharField(verbose_name="상주"),
        ),
    ]
