# Generated by Django 5.1 on 2026-01-02 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("passing_notice", "0005_alter_passingnotice_chief_mourner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passingnotice",
            name="funeral_end_at",
        ),
        migrations.RemoveField(
            model_name="passingnotice",
            name="funeral_start_at",
        ),
    ]
