# Generated by Django 5.1 on 2026-01-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passing_notice", "0006_remove_passingnotice_funeral_end_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passingnotice",
            name="funeral_mass_at",
            field=models.DateTimeField(verbose_name="장례미사 일정"),
        ),
    ]
