# Generated by Django 5.1 on 2025-12-16 02:23

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("body", django_ckeditor_5.fields.CKEditor5Field(verbose_name="본문")),
            ],
            options={
                "verbose_name": "공지사항",
                "verbose_name_plural": "공지사항",
                "db_table": "notice",
                "ordering": ["-created_at"],
            },
        ),
    ]
