# Generated by Django 5.1 on 2025-12-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="is_fixed",
            field=models.BooleanField(default=False, verbose_name="고정여부"),
        ),
    ]
