# Generated by Django 5.1 on 2025-12-17 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0002_notice_is_fixed"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoticeFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("file", models.FileField(max_length=1000, upload_to="notice/file/", verbose_name="파일")),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_set",
                        related_query_name="file",
                        to="notice.notice",
                        verbose_name="공지사항",
                    ),
                ),
            ],
            options={
                "verbose_name": "공지사항 파일",
                "verbose_name_plural": "공지사항 파일",
                "db_table": "notice_file",
            },
        ),
    ]
