# Generated by Django 5.1 on 2026-01-07 03:27

from django.db import migrations, models

import app.common.storages


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0003_noticefile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticefile",
            name="file",
            field=models.FileField(
                max_length=1000,
                storage=app.common.storages.DownloadableMediaStorage(),
                upload_to="notice/file/",
                verbose_name="파일",
            ),
        ),
    ]
