# Generated by Django 4.2.3 on 2025-12-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("file", models.FileField(max_length=1000, upload_to="document/", verbose_name="자료")),
            ],
            options={
                "verbose_name": "자료",
                "verbose_name_plural": "자료",
                "db_table": "document",
                "ordering": ["-created_at"],
            },
        ),
    ]
