# Generated by Django 4.2.3 on 2025-12-16 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="file",
        ),
        migrations.CreateModel(
            name="DocumentFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("file", models.FileField(max_length=1000, upload_to="document/file/", verbose_name="자료")),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_set",
                        related_query_name="file",
                        to="document.document",
                        verbose_name="자료",
                    ),
                ),
            ],
            options={
                "verbose_name": "파일",
                "verbose_name_plural": "파일",
                "db_table": "document_file",
            },
        ),
    ]
