# Generated by Django 5.1 on 2025-12-18 03:22

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="body",
            field=django_ckeditor_5.fields.CKEditor5Field(default="", verbose_name="본문"),
            preserve_default=False,
        ),
    ]
