# Generated by Django 5.1 on 2026-01-07 03:27

import app.common.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0002_document_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentfile",
            name="file",
            field=models.FileField(
                max_length=1000,
                storage=app.common.storages.DownloadableMediaStorage(),
                upload_to="document/file/",
                verbose_name="자료",
            ),
        ),
    ]
