# Generated by Django 5.1 on 2025-12-16 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("board", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardHit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP 주소")),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="board.board", verbose_name="자유 게시글"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                        verbose_name="유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "자유 게시글 조회",
                "verbose_name_plural": "자유 게시글 조회",
                "db_table": "board_hit",
                "ordering": ["-updated_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("board", "user"), name="unique_board_user_hit"),
                    models.UniqueConstraint(fields=("board", "ip_address"), name="unique_board_ip_hit"),
                ],
            },
        ),
    ]
