# Generated by Django 4.2.3 on 2025-12-12 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_grade"),
        ("board_hit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardhit",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name="IP 주소"),
        ),
        migrations.AlterField(
            model_name="boardhit",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="user.user", verbose_name="유저"
            ),
        ),
        migrations.AddConstraint(
            model_name="boardhit",
            constraint=models.UniqueConstraint(fields=("board", "user"), name="unique_user_hit"),
        ),
        migrations.AddConstraint(
            model_name="boardhit",
            constraint=models.UniqueConstraint(fields=("board", "ip_address"), name="unique_ip_hit"),
        ),
    ]
