# Generated by Django 4.2.3 on 2025-12-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_hit", "0002_boardhit_ip_address_alter_boardhit_user_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="boardhit",
            name="unique_user_hit",
        ),
        migrations.RemoveConstraint(
            model_name="boardhit",
            name="unique_ip_hit",
        ),
        migrations.AddConstraint(
            model_name="boardhit",
            constraint=models.UniqueConstraint(fields=("board", "user"), name="unique_board_user_hit"),
        ),
        migrations.AddConstraint(
            model_name="boardhit",
            constraint=models.UniqueConstraint(fields=("board", "ip_address"), name="unique_board_ip_hit"),
        ),
    ]
