# Generated by Django 4.2.3 on 2025-12-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailVerifier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                ("code", models.CharField(max_length=6, verbose_name="인증번호")),
                ("token", models.CharField(max_length=40, verbose_name="토큰")),
            ],
            options={
                "db_table": "email_verifier",
                "ordering": ["-created_at"],
            },
        ),
    ]
