# Generated by Django 4.2.3 on 2025-12-12 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_verifier", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailverifier",
            options={"ordering": ["-created_at"], "verbose_name": "이메일 검증", "verbose_name_plural": "이메일 검증"},
        ),
    ]
