# Generated by Django 5.1 on 2025-12-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PriestHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("order", models.PositiveIntegerField(db_index=True, editable=False, verbose_name="order")),
                ("name", models.CharField(max_length=20, verbose_name="이름")),
                ("baptismal_name", models.CharField(max_length=40, verbose_name="세례명")),
                ("ordination_date", models.DateField(verbose_name="수품일")),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PASTOR", "주임신부"),
                            ("ASSOCIATE", "부주임신부 및 보좌신부"),
                            ("PRIEST", "사제"),
                            ("RELIGIOUS", "수도자"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="직책",
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        blank=True, help_text="예: 제1대 주임신부", max_length=50, null=True, verbose_name="구분"
                    ),
                ),
                (
                    "assistant_system",
                    models.CharField(
                        blank=True,
                        help_text="부주임신부에게만 사용",
                        max_length=50,
                        null=True,
                        verbose_name="보좌 체제",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="재임 시작일")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="재임 종료일")),
            ],
            options={
                "verbose_name": "본당 출신 사제",
                "verbose_name_plural": "본당 출신 사제",
                "db_table": "priest_history",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AssociateHistory",
            fields=[],
            options={
                "verbose_name": "역대 부주임/보좌신부",
                "verbose_name_plural": "역대 부주임/보좌신부",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("priest_history.priesthistory",),
        ),
        migrations.CreateModel(
            name="PastorHistory",
            fields=[],
            options={
                "verbose_name": "역대 주임신부",
                "verbose_name_plural": "역대 주임신부",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("priest_history.priesthistory",),
        ),
        migrations.CreateModel(
            name="ReligiousHistory",
            fields=[],
            options={
                "verbose_name": "본당 출신 수도자",
                "verbose_name_plural": "본당 출신 수도자",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("priest_history.priesthistory",),
        ),
    ]
