# Generated by Django 5.1 on 2025-12-26 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("priest_history", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AssociateHistory",
        ),
        migrations.DeleteModel(
            name="PastorHistory",
        ),
        migrations.DeleteModel(
            name="ReligiousHistory",
        ),
        migrations.RemoveField(
            model_name="priesthistory",
            name="assistant_system",
        ),
        migrations.RemoveField(
            model_name="priesthistory",
            name="division",
        ),
        migrations.RemoveField(
            model_name="priesthistory",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="priesthistory",
            name="role",
        ),
        migrations.RemoveField(
            model_name="priesthistory",
            name="start_date",
        ),
    ]
