AWSTemplateFormatVersion: '2010-09-09'

Description:
  'RDS IaC'

Parameters:
  ProjectName:
    Type: String
  ENV:
    Type: String
    AllowedValues:
      - dev
      - prod


Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub '${ProjectName}-${ENV}-db-sg'
      VpcId: {'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-VPC'}
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0

  # DEV
  RDSSecretDev:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/${ENV}/db'
      GenerateSecretString:
        RequireEachIncludedType: True
        SecretStringTemplate: !Sub '{"username": "${ProjectName}"}'
        GenerateStringKey: 'password'
        PasswordLength: 30
        ExcludeCharacters: '"@/\&;='
  RDSSecretAttachmentDev:
    Type: AWS::SecretsManager::SecretTargetAttachment
    DependsOn: RDSDBInstanceDev
    Properties:
      SecretId: !Ref RDSSecretDev
      TargetId: !Ref RDSDBInstanceDev
      TargetType: AWS::RDS::DBInstance
  RDSSubnetGroupDev:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub '${ProjectName}-${ENV}-db-subnet-group'
      DBSubnetGroupDescription: !Sub '${ProjectName}-${ENV}-db-subnet-group'
      SubnetIds:
        - { 'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-PublicSubnet1' }
        - { 'Fn::ImportValue': !Sub '${ProjectName}-${ENV}-PublicSubnet2' }
  RDSDBInstanceDev:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    DependsOn: RDSSecretDev
    Properties:
      DBInstanceIdentifier: !Sub '${ProjectName}-${ENV}-db-instance'
      AllocatedStorage: 50
      DBSubnetGroupName: !Ref RDSSubnetGroupDev
      Engine: postgres
      PubliclyAccessible: true
      DBInstanceClass: db.t4g.small
      EngineVersion: 16.11
      DBParameterGroupName: default.postgres16
      Port: 5432
      DBName: !Ref ProjectName
      MasterUsername: !Join [ '', [ '{{resolve:secretsmanager:', !Ref RDSSecretDev, ':SecretString:username}}' ] ]
      MasterUserPassword: !Join [ '', [ '{{resolve:secretsmanager:', !Ref RDSSecretDev, ':SecretString:password}}' ] ]
      VPCSecurityGroups: [ !GetAtt SecurityGroup.GroupId ]
      EnableCloudwatchLogsExports:
        - postgresql

