# Generated by Django 5.1 on 2025-12-31 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("department_board", "0003_alter_departmentboard_options"),
        ("user", "0006_remove_user_model_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentBoardLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "department_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department_board.departmentboard",
                        verbose_name="분과 게시글",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user", verbose_name="유저"),
                ),
            ],
            options={
                "verbose_name": "분과 게시글 좋아요",
                "verbose_name_plural": "분과 게시글 좋아요",
                "db_table": "department_board_like",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("department_board", "user"), name="unique_department_board_likes")
                ],
            },
        ),
    ]
