# Generated by Django 5.1 on 2026-01-07 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catechism_room", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomReservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("date", models.DateField(verbose_name="예약 날짜")),
                ("start_at", models.TimeField(verbose_name="시작 시간")),
                ("end_at", models.TimeField(verbose_name="종료 시간")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_set",
                        to="catechism_room.catechismroom",
                        verbose_name="교리실",
                    ),
                ),
            ],
            options={
                "verbose_name": "교리실 예약",
                "verbose_name_plural": "교리실 예약",
                "db_table": "room_reservation",
                "ordering": ["-date", "-start_at"],
            },
        ),
    ]
