# Generated by Django 5.1 on 2026-01-12 07:09

import django.db.models.deletion
from django.db import migrations, models


def forwards_create_time_slots(apps, schema_editor):
    RoomTimeSlot = apps.get_model("room_reservation", "RoomTimeSlot")
    RepeatRoomReservation = apps.get_model("room_reservation", "RepeatRoomReservation")
    RoomReservation = apps.get_model("room_reservation", "RoomReservation")

    def get_slot(room_id, start_at, end_at):
        slot, _ = RoomTimeSlot.objects.get_or_create(
            room_id=room_id,
            start_at=start_at,
            end_at=end_at,
        )
        return slot

    for repeat in RepeatRoomReservation.objects.all().iterator():
        slot = get_slot(repeat.room_id, repeat.start_at, repeat.end_at)
        repeat.time_slot_id = slot.id
        repeat.save(update_fields=["time_slot"])

    for reservation in RoomReservation.objects.all().iterator():
        slot = get_slot(reservation.room_id, reservation.start_at, reservation.end_at)
        reservation.time_slot_id = slot.id
        reservation.save(update_fields=["time_slot"])


class Migration(migrations.Migration):

    dependencies = [
        ("room_reservation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomTimeSlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("start_at", models.TimeField(verbose_name="시작 시간")),
                ("end_at", models.TimeField(verbose_name="종료 시간")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slot_set",
                        to="room_reservation.catechismroom",
                        verbose_name="교리실",
                    ),
                ),
            ],
            options={
                "verbose_name": "교리실 타임슬롯",
                "verbose_name_plural": "교리실 타임슬롯",
                "db_table": "room_time_slot",
                "ordering": ["start_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="roomtimeslot",
            constraint=models.UniqueConstraint(fields=("room", "start_at", "end_at"), name="unique_room_time_slot"),
        ),
        migrations.AddField(
            model_name="repeatroomreservation",
            name="time_slot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repeat_reservation_set",
                to="room_reservation.roomtimeslot",
                verbose_name="타임슬롯",
            ),
        ),
        migrations.AddField(
            model_name="roomreservation",
            name="time_slot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservation_set",
                to="room_reservation.roomtimeslot",
                verbose_name="타임슬롯",
            ),
        ),
        migrations.RunPython(forwards_create_time_slots, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="repeatroomreservation",
            name="time_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repeat_reservation_set",
                to="room_reservation.roomtimeslot",
                verbose_name="타임슬롯",
            ),
        ),
        migrations.AlterField(
            model_name="roomreservation",
            name="time_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservation_set",
                to="room_reservation.roomtimeslot",
                verbose_name="타임슬롯",
            ),
        ),
        migrations.RemoveField(
            model_name="repeatroomreservation",
            name="end_at",
        ),
        migrations.RemoveField(
            model_name="repeatroomreservation",
            name="start_at",
        ),
        migrations.RemoveField(
            model_name="roomreservation",
            name="end_at",
        ),
        migrations.RemoveField(
            model_name="roomreservation",
            name="start_at",
        ),
    ]
