# Generated by Django 5.1 on 2026-01-12 07:09

import django.db.models.deletion
from django.db import migrations, models


def forwards_copy_time_fields(apps, schema_editor):
    RepeatRoomReservation = apps.get_model("room_reservation", "RepeatRoomReservation")
    RoomReservation = apps.get_model("room_reservation", "RoomReservation")

    for repeat in RepeatRoomReservation.objects.select_related("time_slot").iterator():
        update_fields = []
        if repeat.time_slot_id:
            repeat.start_at = repeat.time_slot.start_at
            repeat.end_at = repeat.time_slot.end_at
            update_fields.extend(["start_at", "end_at"])

        if repeat.repeat_type == "daily":
            repeat.repeat_type = "weekly"
            repeat.weekdays = [0, 1, 2, 3, 4, 5, 6]
            update_fields.extend(["repeat_type", "weekdays"])
        elif repeat.repeat_type == "monthly":
            repeat.repeat_type = "monthly_date"
            if repeat.start_date:
                repeat.month_day = repeat.start_date.day
                update_fields.append("month_day")
            update_fields.append("repeat_type")

        if update_fields:
            repeat.save(update_fields=sorted(set(update_fields)))

    for reservation in RoomReservation.objects.select_related("time_slot").iterator():
        if reservation.time_slot_id:
            reservation.start_at = reservation.time_slot.start_at
            reservation.end_at = reservation.time_slot.end_at
            reservation.save(update_fields=["start_at", "end_at"])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("user", "0006_remove_user_model_test"),
        ("room_reservation", "0002_room_time_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="repeatroomreservation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="repeat_room_reservation_set",
                to="user.user",
                verbose_name="예약 생성자",
            ),
        ),
        migrations.AddField(
            model_name="repeatroomreservation",
            name="user_name",
            field=models.CharField(default="", max_length=10, verbose_name="사용자명"),
        ),
        migrations.AddField(
            model_name="repeatroomreservation",
            name="start_at",
            field=models.TimeField(null=True, verbose_name="시작 시간"),
        ),
        migrations.AddField(
            model_name="repeatroomreservation",
            name="end_at",
            field=models.TimeField(null=True, verbose_name="종료 시간"),
        ),
        migrations.AddField(
            model_name="repeatroomreservation",
            name="week_of_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="반복 주차"),
        ),
        migrations.AddField(
            model_name="repeatroomreservation",
            name="month_day",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="반복 일자"),
        ),
        migrations.AddField(
            model_name="roomreservation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="room_reservation_set",
                to="user.user",
                verbose_name="예약 생성자",
            ),
        ),
        migrations.AddField(
            model_name="roomreservation",
            name="user_name",
            field=models.CharField(default="", max_length=10, verbose_name="사용자명"),
        ),
        migrations.AddField(
            model_name="roomreservation",
            name="start_at",
            field=models.TimeField(null=True, verbose_name="시작 시간"),
        ),
        migrations.AddField(
            model_name="roomreservation",
            name="end_at",
            field=models.TimeField(null=True, verbose_name="종료 시간"),
        ),
        migrations.AlterField(
            model_name="repeatroomreservation",
            name="title",
            field=models.CharField(max_length=50, verbose_name="예약 제목"),
        ),
        migrations.AlterField(
            model_name="repeatroomreservation",
            name="repeat_type",
            field=models.CharField(
                choices=[("weekly", "요일 반복"), ("monthly_date", "날짜 반복")],
                max_length=20,
                verbose_name="반복 유형",
            ),
        ),
        migrations.AlterField(
            model_name="roomreservation",
            name="title",
            field=models.CharField(max_length=50, verbose_name="예약 제목"),
        ),
        migrations.RunPython(forwards_copy_time_fields, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="repeatroomreservation",
            name="time_slot",
        ),
        migrations.RemoveField(
            model_name="roomreservation",
            name="time_slot",
        ),
        migrations.DeleteModel(
            name="RoomTimeSlot",
        ),
        migrations.AlterField(
            model_name="repeatroomreservation",
            name="start_at",
            field=models.TimeField(verbose_name="시작 시간"),
        ),
        migrations.AlterField(
            model_name="repeatroomreservation",
            name="end_at",
            field=models.TimeField(verbose_name="종료 시간"),
        ),
        migrations.AlterField(
            model_name="roomreservation",
            name="start_at",
            field=models.TimeField(verbose_name="시작 시간"),
        ),
        migrations.AlterField(
            model_name="roomreservation",
            name="end_at",
            field=models.TimeField(verbose_name="종료 시간"),
        ),
    ]
