# Generated by Django 5.1 on 2026-02-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room_reservation", "0003_time_slot_to_time_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="catechismroom",
            name="building",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="건물명"),
        ),
        migrations.RemoveField(
            model_name="catechismroom",
            name="description",
        ),
    ]
