# Generated by Django 5.1 on 2026-02-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_reservation", "0004_catechism_room_building"),
    ]

    operations = [
        migrations.AddField(
            model_name="repeatroomreservation",
            name="organization_name",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="사용단체명"),
        ),
        migrations.AddField(
            model_name="roomreservation",
            name="organization_name",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="사용단체명"),
        ),
    ]
