# Generated by Django 5.1 on 2025-12-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_board_is_modified_boardcomment_is_modified"),
        ("board_like", "0001_initial"),
        ("user", "0004_alter_user_grade"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="boardlike",
            name="unique_likes",
        ),
        migrations.AddConstraint(
            model_name="boardlike",
            constraint=models.UniqueConstraint(fields=("board", "user"), name="unique_board_likes"),
        ),
    ]
