# Generated by Django 4.2.3 on 2025-12-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_like", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="boardlike",
            constraint=models.UniqueConstraint(fields=("board", "user"), name="unique_likes"),
        ),
    ]
