# Generated by Django 5.1 on 2025-12-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Religious",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("order", models.PositiveIntegerField(db_index=True, editable=False, verbose_name="order")),
                ("image", models.CharField(max_length=1000, verbose_name="이미지")),
                ("category", models.CharField(max_length=50, verbose_name="구분")),
                ("name", models.CharField(max_length=20, verbose_name="이름")),
                ("baptismal_name", models.CharField(max_length=40, verbose_name="세례명")),
                ("start_date", models.DateField(verbose_name="재임 시작일")),
            ],
            options={
                "verbose_name": "수도자",
                "verbose_name_plural": "수도자",
                "db_table": "religious",
                "ordering": ["order"],
            },
        ),
    ]
