# Generated by Django 5.1 on 2025-12-26 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("religious", "0002_religious_end_date_religious_is_retired_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="religious",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="religious",
            name="is_retired",
        ),
    ]
