# Generated by Django 5.1 on 2025-12-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("religious", "0003_remove_religious_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="religious",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="구분"),
        ),
    ]
