# Generated by Django 5.1 on 2025-12-31 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("religious", "0004_alter_religious_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="religious",
            options={"ordering": ["start_date", "category"], "verbose_name": "수도자", "verbose_name_plural": "수도자"},
        ),
    ]
