# Generated by Django 5.1 on 2025-12-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("scheduled_at", models.DateField(verbose_name="날짜")),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, help_text="입력하지 않은 경우 하루종일", null=True, verbose_name="시작시간"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, help_text="입력하지 않은 경우 하루종일", null=True, verbose_name="종료시간"
                    ),
                ),
            ],
            options={
                "verbose_name": "일정",
                "verbose_name_plural": "일정",
                "db_table": "schedule",
                "ordering": ["scheduled_at"],
            },
        ),
    ]
