# Generated by Django 5.1 on 2025-12-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="location",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="장소"),
        ),
    ]
