# Generated by Django 4.2.3 on 2025-12-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_alter_schedule_end_time_alter_schedule_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="end_time",
            field=models.TimeField(blank=True, help_text="입력하지 않은 경우 하루종일", null=True, verbose_name="종료시간"),
        ),
    ]
