# Generated by Django 5.1 on 2025-12-16 02:23

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("body", django_ckeditor_5.fields.CKEditor5Field(verbose_name="본문")),
                ("hit_count", models.PositiveBigIntegerField(default=0, editable=False, verbose_name="조회수")),
                ("comment_count", models.PositiveBigIntegerField(default=0, editable=False, verbose_name="댓글수")),
                ("like_count", models.PositiveBigIntegerField(default=0, editable=False, verbose_name="좋아요수")),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user", verbose_name="유저"),
                ),
            ],
            options={
                "verbose_name": "자유 게시글",
                "verbose_name_plural": "자유 게시글",
                "db_table": "board",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BoardComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("body", models.CharField(max_length=500, verbose_name="내용")),
                ("is_deleted", models.BooleanField(default=False, editable=False, verbose_name="삭제여부")),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="board.board", verbose_name="자유 게시글"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_set",
                        related_query_name="child",
                        to="board.boardcomment",
                        verbose_name="부모 댓글",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user", verbose_name="유저"),
                ),
            ],
            options={
                "verbose_name": "자유 게시글 댓글",
                "verbose_name_plural": "자유 게시글 댓글",
                "db_table": "board_comment",
                "ordering": ["-created_at"],
            },
        ),
    ]
