# Generated by Django 4.2.3 on 2025-12-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
            ],
            options={
                "verbose_name": "자유 게시글",
                "verbose_name_plural": "자유 게시글",
                "db_table": "board",
                "ordering": ["-created_at"],
            },
        ),
    ]
