# Generated by Django 4.2.3 on 2025-12-12 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_grade"),
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="body",
            field=models.TextField(default="", verbose_name="본문"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="board",
            name="comment_count",
            field=models.PositiveBigIntegerField(default=0, verbose_name="댓글수"),
        ),
        migrations.AddField(
            model_name="board",
            name="hit_count",
            field=models.PositiveBigIntegerField(default=0, verbose_name="조회수"),
        ),
        migrations.AddField(
            model_name="board",
            name="like_count",
            field=models.PositiveBigIntegerField(default=0, verbose_name="좋아요수"),
        ),
        migrations.AddField(
            model_name="board",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="user.user", verbose_name="유저"
            ),
            preserve_default=False,
        ),
    ]
