# Generated by Django 5.1 on 2025-12-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="is_modified",
            field=models.BooleanField(default=False, editable=False, verbose_name="수정여부"),
        ),
        migrations.AddField(
            model_name="boardcomment",
            name="is_modified",
            field=models.BooleanField(default=False, editable=False, verbose_name="수정여부"),
        ),
    ]
