# Generated by Django 5.1 on 2026-01-09 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_board_is_modified_boardcomment_is_modified"),
        ("user", "0006_remove_user_model_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardcomment",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="user.user", verbose_name="유저"
            ),
        ),
    ]
