# Generated by Django 4.2.3 on 2025-12-12 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_grade"),
        ("board", "0002_board_body_board_comment_count_board_hit_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("body", models.CharField(max_length=500, verbose_name="내용")),
                ("is_deleted", models.BooleanField(default=False, editable=False, verbose_name="삭제여부")),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="board.board", verbose_name="자유 게시글"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_set",
                        related_query_name="child",
                        to="board.boardcomment",
                        verbose_name="부모 댓글",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user", verbose_name="유저"),
                ),
            ],
            options={
                "verbose_name": "자유 게시글 댓글",
                "verbose_name_plural": "자유 게시글 댓글",
                "db_table": "board_comment",
                "ordering": ["-created_at"],
            },
        ),
    ]
