# Generated by Django 4.2.3 on 2025-12-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_boardcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="comment_count",
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name="댓글수"),
        ),
        migrations.AlterField(
            model_name="board",
            name="hit_count",
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name="조회수"),
        ),
        migrations.AlterField(
            model_name="board",
            name="like_count",
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name="좋아요수"),
        ),
    ]
