# Generated by Django 5.1 on 2026-01-09 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_alter_boardcomment_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("image", models.ImageField(max_length=1000, upload_to="board/image/", verbose_name="이미지")),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_set",
                        related_query_name="image",
                        to="board.board",
                        verbose_name="자유 게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "자유 게시글 이미지",
                "verbose_name_plural": "자유 게시글 이미지",
                "db_table": "board_image",
                "ordering": ["created_at"],
            },
        ),
    ]
