# Generated by Django 4.2.3 on 2025-12-12 06:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0004_alter_board_comment_count_alter_board_hit_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="body",
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name="본문"),
        ),
    ]
