# Generated by Django 5.1 on 2025-12-23 05:36

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PastoralGuidelines",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "image",
                    models.ImageField(max_length=1000, upload_to="pastoral_guideline/image/", verbose_name="이미지"),
                ),
                ("category", models.CharField(max_length=100, verbose_name="카테고리명")),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("subtitle", models.CharField(blank=True, max_length=500, null=True, verbose_name="서브 제목")),
                ("body", django_ckeditor_5.fields.CKEditor5Field(verbose_name="내용")),
                ("signature_text", models.CharField(max_length=100, verbose_name="서명 텍스트")),
                (
                    "signature_image",
                    models.ImageField(
                        max_length=1000, upload_to="pastoral_guideline/signature/", verbose_name="서명 이미지"
                    ),
                ),
            ],
            options={
                "verbose_name": "사목지침",
                "verbose_name_plural": "사목지침",
                "db_table": "pastoral_guidelines",
            },
        ),
    ]
