# Generated by Django 4.2.3 on 2025-12-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_log", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emaillog",
            name="to_set",
        ),
        migrations.AddField(
            model_name="emaillog",
            name="email",
            field=models.EmailField(default="", max_length=254, verbose_name="수신자"),
            preserve_default=False,
        ),
    ]
