# Generated by Django 5.1 on 2025-12-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("religious_history", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="religioushistory",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="구분"),
        ),
    ]
