# Generated by Django 5.1 on 2025-12-31 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("religious_history", "0002_alter_religioushistory_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="religioushistory",
            options={
                "ordering": ["start_date", "category"],
                "verbose_name": "본당출신 수도자",
                "verbose_name_plural": "본당출신 수도자",
            },
        ),
    ]
