# Generated by Django 5.1 on 2026-01-06 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("religious_history", "0003_alter_religioushistory_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="religioushistory",
            options={
                "ordering": ["start_date", "category"],
                "verbose_name": "역대 수도자",
                "verbose_name_plural": "역대 수도자",
            },
        ),
    ]
