# Generated by Django 5.1 on 2026-01-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CatechismRoom",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("name", models.CharField(max_length=50, verbose_name="교리실명")),
                ("location", models.TextField(blank=True, default="", verbose_name="위치")),
                ("description", models.TextField(blank=True, default="", verbose_name="설명")),
            ],
            options={
                "verbose_name": "교리실",
                "verbose_name_plural": "교리실",
                "db_table": "catechism_room",
                "ordering": ["-created_at"],
            },
        ),
    ]
