from django.urls import include, path

urlpatterns = [
    path("v1/", include("app.user.v1.urls")),
    path("v1/", include("app.department.v1.urls")),
    path("v1/", include("app.presigned_url.v1.urls")),
    path("v1/", include("app.email_verifier.v1.urls")),
    path("v1/", include("app.notice.v1.urls")),
    path("v1/", include("app.notice_file.v1.urls")),
    path("v1/", include("app.news.v1.urls")),
    path("v1/", include("app.weekly_bulletin.v1.urls")),
    path("v1/", include("app.weekly_bulletin_editorial.v1.urls")),
    path("v1/", include("app.passing_notice.v1.urls")),
    path("v1/", include("app.passing_notice_comment.v1.urls")),
    path("v1/", include("app.liturgy_flower.v1.urls")),
    path("v1/", include("app.liturgy_flower_comment.v1.urls")),
    path("v1/", include("app.liturgy_flower_like.v1.urls")),
    path("v1/", include("app.board.v1.urls")),
    path("v1/", include("app.board_comment.v1.urls")),
    path("v1/", include("app.board_like.v1.urls")),
    path("v1/", include("app.document.v1.urls")),
    path("v1/", include("app.pastoral_guidelines.v1.urls")),
    path("v1/", include("app.schedule.v1.urls")),
    path("v1/", include("app.contact.v1.urls")),
    path("v1/", include("app.banner.v1.urls")),
    path("v1/", include("app.priest.v1.urls")),
    path("v1/", include("app.religious.v1.urls")),
    path("v1/", include("app.priest_history.v1.urls")),
    path("v1/", include("app.religious_history.v1.urls")),
    path("v1/", include("app.pastor_history.v1.urls")),
    path("v1/", include("app.assistant_priest_history.v1.urls")),
]
