# Generated by Django 5.1 on 2025-12-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Priest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("order", models.PositiveIntegerField(db_index=True, editable=False, verbose_name="order")),
                ("image", models.ImageField(max_length=1000, upload_to="priest/image/", verbose_name="이미지")),
                ("name", models.CharField(max_length=20, verbose_name="이름")),
                ("baptismal_name", models.CharField(max_length=40, verbose_name="세례명")),
                ("ordination_date", models.DateField(verbose_name="수품일")),
                ("is_retired", models.BooleanField(default=False, verbose_name="퇴임 여부")),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[("PASTOR", "주임신부"), ("ASSOCIATE", "부주임신부 및 보좌신부")],
                        max_length=10,
                        null=True,
                        verbose_name="직책 구분",
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        blank=True, help_text="예: 제1대 주임신부", max_length=50, null=True, verbose_name="구분"
                    ),
                ),
                (
                    "assistant_system",
                    models.CharField(
                        blank=True,
                        help_text="부주임신부에게만 사용",
                        max_length=50,
                        null=True,
                        verbose_name="보좌 체제",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="재임 시작일")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="재임 종료일")),
            ],
            options={
                "verbose_name": "사제",
                "verbose_name_plural": "사제",
                "db_table": "priest",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Associate",
            fields=[],
            options={
                "verbose_name": "부주임/보좌신부",
                "verbose_name_plural": "부주임/보좌신부",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("priest.priest",),
        ),
        migrations.CreateModel(
            name="Pastor",
            fields=[],
            options={
                "verbose_name": "주임신부",
                "verbose_name_plural": "주임신부",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("priest.priest",),
        ),
    ]
