# Generated by Django 5.1 on 2025-12-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("priest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="priest",
            name="is_retired",
            field=models.BooleanField(default=False, verbose_name="퇴임 여부"),
        ),
        migrations.AlterField(
            model_name="priest",
            name="image",
            field=models.ImageField(max_length=1000, upload_to="priest/image/", verbose_name="이미지"),
        ),
    ]
