# Generated by Django 5.1 on 2025-12-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("priest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="priest",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("PASTOR", "주임신부"), ("ASSOCIATE", "부주임신부 및 보좌신부")],
                max_length=10,
                null=True,
                verbose_name="직책 부여",
            ),
        ),
        migrations.AlterField(
            model_name="priest",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="재임 시작일"),
        ),
    ]
