# Generated by Django 5.1 on 2025-12-26 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("priest", "0002_alter_priest_role_alter_priest_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriestAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("order", models.PositiveIntegerField(db_index=True, editable=False, verbose_name="order")),
                (
                    "role",
                    models.CharField(
                        choices=[("PASTOR", "주임신부"), ("ASSOCIATE", "부주임/보좌신부")],
                        max_length=10,
                        verbose_name="직책",
                    ),
                ),
                ("division", models.CharField(help_text="예: 제1대 주임신부", max_length=50, verbose_name="구분")),
                (
                    "assistant_system",
                    models.CharField(
                        blank=True,
                        help_text="부주임/보좌신부의 경우 입력해주세요",
                        max_length=50,
                        null=True,
                        verbose_name="보좌 체제",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="재임 시작일")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="재임 종료일")),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "재임중"), ("ENDED", "종료")], max_length=10, verbose_name="재임 상태"
                    ),
                ),
            ],
            options={
                "verbose_name": "사제 배정",
                "verbose_name_plural": "사제 배정",
                "db_table": "priest_assignment",
                "ordering": ["order"],
            },
        ),
        migrations.DeleteModel(
            name="Associate",
        ),
        migrations.DeleteModel(
            name="Pastor",
        ),
        migrations.RemoveField(
            model_name="priest",
            name="assistant_system",
        ),
        migrations.RemoveField(
            model_name="priest",
            name="division",
        ),
        migrations.RemoveField(
            model_name="priest",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="priest",
            name="is_retired",
        ),
        migrations.RemoveField(
            model_name="priest",
            name="role",
        ),
        migrations.RemoveField(
            model_name="priest",
            name="start_date",
        ),
        migrations.AddField(
            model_name="priestassignment",
            name="priest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="priest.priest",
                verbose_name="사제",
            ),
        ),
    ]
