# Generated by Django 5.1 on 2025-12-26 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("priest", "0003_priestassignment_delete_associate_delete_pastor_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PriestAssignment",
        ),
    ]
