# Generated by Django 5.1 on 2025-12-31 00:50

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("priest", "0004_delete_priestassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="priest",
            name="start_date",
            field=models.DateField(default=datetime.date(2025, 12, 31), verbose_name="재임 시작일"),
            preserve_default=False,
        ),
    ]
