# Generated by Django 4.2.3 on 2025-12-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("office_phone", models.CharField(max_length=13, verbose_name="사무실 연락처")),
                ("president_name", models.CharField(max_length=40, verbose_name="연령회장 이름")),
                ("president_phone", models.CharField(max_length=13, verbose_name="연령회장 연락처")),
            ],
            options={
                "verbose_name": "연락처",
                "verbose_name_plural": "연락처",
                "db_table": "contact",
            },
        ),
    ]
