# Generated by Django 5.1 on 2025-12-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("name", models.CharField(max_length=100, verbose_name="분과명")),
            ],
            options={
                "verbose_name": "분과",
                "verbose_name_plural": "분과",
                "db_table": "department",
                "ordering": ["name"],
            },
        ),
    ]
