# Generated by Django 4.2.3 on 2025-12-12 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ["name"], "verbose_name": "분과", "verbose_name_plural": "분과"},
        ),
        migrations.RemoveField(
            model_name="department",
            name="order",
        ),
    ]
