# Generated by Django 5.1 on 2025-12-16 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubDepartment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("name", models.CharField(max_length=100, verbose_name="세부분과명")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_department_set",
                        related_query_name="sub_department",
                        to="department.department",
                        verbose_name="분과",
                    ),
                ),
            ],
            options={
                "verbose_name": "세부분과",
                "verbose_name_plural": "세부분과",
                "db_table": "sub_department",
                "ordering": ["name"],
            },
        ),
    ]
