# Generated by Django 5.1 on 2025-12-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0002_subdepartment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subdepartment",
            options={"ordering": ["order"], "verbose_name": "세부분과", "verbose_name_plural": "세부분과"},
        ),
        migrations.AddField(
            model_name="subdepartment",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name="order"),
            preserve_default=False,
        ),
    ]
