# Generated by Django 5.1 on 2026-01-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0004_remove_subdepartment_name_prefix"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ["order"], "verbose_name": "분과", "verbose_name_plural": "분과"},
        ),
        migrations.AddField(
            model_name="department",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name="order"),
            preserve_default=False,
        ),
    ]
