# Generated by Django 5.1 on 2025-12-31 03:08

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("department", "0004_remove_subdepartment_name_prefix"),
        ("user", "0006_remove_user_model_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentBoard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("body", django_ckeditor_5.fields.CKEditor5Field(verbose_name="본문")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="department.department", verbose_name="분과"
                    ),
                ),
                (
                    "sub_department_set",
                    models.ManyToManyField(
                        blank=True, null=True, to="department.subdepartment", verbose_name="세부분과"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user", verbose_name="유저"),
                ),
            ],
            options={
                "verbose_name": "DepartmentBoard",
                "verbose_name_plural": "DepartmentBoard",
                "db_table": "department_board",
                "ordering": ["-created_at"],
            },
        ),
    ]
