# Generated by Django 5.1 on 2025-12-31 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department_board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentboard",
            name="comment_count",
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name="댓글수"),
        ),
        migrations.AddField(
            model_name="departmentboard",
            name="hit_count",
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name="조회수"),
        ),
        migrations.AddField(
            model_name="departmentboard",
            name="is_modified",
            field=models.BooleanField(default=False, editable=False, verbose_name="수정여부"),
        ),
        migrations.AddField(
            model_name="departmentboard",
            name="like_count",
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name="좋아요수"),
        ),
    ]
