# Generated by Django 5.1 on 2025-12-31 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("department_board", "0002_departmentboard_comment_count_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="departmentboard",
            options={"ordering": ["-created_at"], "verbose_name": "분과 게시글", "verbose_name_plural": "분과 게시글"},
        ),
    ]
