# Generated by Django 5.1 on 2025-12-31 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department_board", "0003_alter_departmentboard_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentBoardImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "image",
                    models.ImageField(max_length=1000, upload_to="department_board/image/", verbose_name="이미지"),
                ),
                (
                    "department_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images_set",
                        related_query_name="image",
                        to="department_board.departmentboard",
                        verbose_name="분과 게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "분과 게시글 이미지",
                "verbose_name_plural": "분과 게시글 이미지",
                "db_table": "department_board_image",
                "ordering": ["-created_at"],
            },
        ),
    ]
