# Generated by Django 5.1 on 2026-01-05 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0004_remove_subdepartment_name_prefix"),
        ("department_board", "0005_alter_departmentboardimage_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departmentboard",
            name="sub_department_set",
        ),
        migrations.AddField(
            model_name="departmentboard",
            name="sub_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="department.subdepartment",
                verbose_name="세부분과",
            ),
        ),
    ]
