# Generated by Django 5.1 on 2026-01-06 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0004_remove_subdepartment_name_prefix"),
        ("department_board", "0006_remove_departmentboard_sub_department_set_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmentboard",
            name="sub_department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="department.subdepartment", verbose_name="세부분과"
            ),
        ),
    ]
