# Generated by Django 5.1 on 2026-01-07 02:59

import app.common.storages
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department_board", "0007_alter_departmentboard_sub_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentBoardFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "file",
                    models.FileField(
                        max_length=1000,
                        storage=app.common.storages.DownloadableMediaStorage(),
                        upload_to="department_board/file/",
                        verbose_name="분과게시글 파일",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="파일명")),
                (
                    "department_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_set",
                        related_query_name="file",
                        to="department_board.departmentboard",
                        verbose_name="분과 게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "분과 게시글 파일",
                "verbose_name_plural": "분과 게시글 파일",
                "db_table": "department_board_file",
                "ordering": ["created_at"],
            },
        ),
    ]
