# Generated by Django 5.1 on 2026-01-08 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("department_board", "0008_departmentboardfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departmentboardfile",
            name="file_name",
        ),
    ]
