# Generated by Django 5.1 on 2026-01-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department_board", "0011_departmentboard_is_pinned"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentboard",
            name="is_secret",
            field=models.BooleanField(default=False, verbose_name="비밀글"),
        ),
    ]
