# Generated by Django 5.1 on 2026-02-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("department_board", "0012_departmentboard_is_secret"),
    ]

    operations = [
        migrations.RenameField(
            model_name="departmentboard",
            old_name="is_pinned",
            new_name="is_fixed",
        ),
    ]
